import type {
  ActionablePrompt,
  BridgePairWatchDeviceProjection,
  BridgePairWatchRequest,
  BridgePairWatchResponse,
  BridgeStatus,
  CanonicalEvent,
  CanonicalSessionState,
  CommandEnvelope,
  CommandResult,
  EntityType,
  EventCursor,
  EventType,
  HandleSessionRequest,
  HostEnrollmentRequest,
  HostEnrollmentResponse,
  HostMetadataUpdateRequest,
  HostPlatform,
  HostProjection,
  HostWatchLink,
  IdentityAlgorithm,
  IdentityRevokeRequest,
  IdentityRevokeResponse,
  IdentityStatus,
  KeyRotationRequest,
  KeyRotationResponse,
  KeyStatus,
  LinkRevokeReason,
  LinkedWatchProjection,
  MarkSessionReadRequest,
  MarkSessionReadResponse,
  NormalizedMarkSessionReadRequest,
  PublicIdentity,
  SessionHandleAction,
  SessionHandleActorKind,
  SessionReadSource,
  SessionStatus,
  SessionSummaryAssistant,
  SignedRequestHeaders,
  ValidationResult,
} from '../src';

// This file is compiled by the protocol strict typecheck. Keeping the intended
// public contracts in one tuple makes accidental barrel removals a compile error.
type IntendedPublicContracts = [
  ActionablePrompt,
  BridgePairWatchDeviceProjection,
  BridgePairWatchRequest,
  BridgePairWatchResponse,
  BridgeStatus,
  CanonicalEvent,
  CanonicalSessionState,
  CommandEnvelope,
  CommandResult,
  EntityType,
  EventCursor,
  EventType,
  HandleSessionRequest,
  HostEnrollmentRequest,
  HostEnrollmentResponse,
  HostMetadataUpdateRequest,
  HostPlatform,
  HostProjection,
  HostWatchLink,
  IdentityAlgorithm,
  IdentityRevokeRequest,
  IdentityRevokeResponse,
  IdentityStatus,
  KeyRotationRequest,
  KeyRotationResponse,
  KeyStatus,
  LinkRevokeReason,
  LinkedWatchProjection,
  MarkSessionReadRequest,
  MarkSessionReadResponse,
  NormalizedMarkSessionReadRequest,
  PublicIdentity,
  SessionHandleAction,
  SessionHandleActorKind,
  SessionReadSource,
  SessionStatus,
  SessionSummaryAssistant,
  SignedRequestHeaders,
  ValidationResult<unknown>,
];

const handleAction: SessionHandleAction = 'watch_reply';
const pairWatchDevice: BridgePairWatchDeviceProjection = {
  watchDeviceId: 'watch_public-contract',
  selectedHostIds: ['host_public-contract'],
  registeredAt: '2026-07-16T00:00:00.000Z',
  lastSeenAt: '2026-07-16T00:00:00.000Z',
  pairingStatus: 'paired',
};

void (null as unknown as IntendedPublicContracts);
void handleAction;
void pairWatchDevice;
